services:
  - type: web
    name: evm-voting-system
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    headers:
      - source: "/*"
        headers:
          - key: "Cache-Control"
            value: "no-cache"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
